/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/images/models/environment.glb 
*/

import { useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from "three";
import { uniform } from 'three/tsl';


export default function Environment({shaderUniforms,Fragmentobject,Vertexobject, ...props}) {
  const { nodes, materials } = useGLTF('images/models/environment.glb')

  useEffect(()=>{
    Object.values(nodes).forEach((node)=>{
      if(node.isMesh && node.material){
        node.material= new THREE.MeshBasicMaterial({color: 'red'});  
        node.material.needsUpdate=true;
        console.log(node.material.map)
        // const originalColor=node.material.color.clone()
        // const uniforms={
        //   ...shaderUniforms,
        // }
        // uniforms.uColor={value:originalColor}
        
        // node.material= new THREE.ShaderMaterial({
        //     vertexShader: Vertexobject,
        //     fragmentShader: Fragmentobject,
        //     uniforms:uniforms,
      
        //   })
      }
      
      

    })
  },[nodes])
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} position={[-53.705, 0, -51.512]} rotation={[0, 0.883, 0]} scale={[182.556, 17.701, 144.595]} />
      <mesh geometry={nodes.phoneScreen.geometry} material={materials['Black Screen']} position={[-85.65, 1.538, -87.21]} rotation={[-1.773, -0.27, -2.793]} scale={[1, 0.054, 2.074]} />
      <mesh geometry={nodes.phoneCase.geometry} material={materials['Phone case']} position={[-85.656, 1.533, -87.226]} rotation={[-1.773, -0.27, -2.793]} scale={[1.107, 0.104, 2.092]} />
      <mesh geometry={nodes.laptopShellBottom.geometry} material={materials.white} position={[-65.088, 0.458, -45.387]} rotation={[-1.463, 0.431, -2.126]} scale={[3.413, 2.526, 0.073]} />
      <mesh geometry={nodes.laptopKeyboard.geometry} material={materials['grey keyboard']} position={[-67.296, 1.284, -43.694]} rotation={[0.701, 0.882, -0.717]} scale={[0.3, 0.035, 0.212]} />
      <mesh geometry={nodes.laptopHeadShell.geometry} material={materials.white} position={[-66.307, 3.85, -46.554]} rotation={[1.571, -0.26, -1.053]} scale={[-3.413, -0.085, -2.526]} />
      <mesh geometry={nodes.laptopScreen.geometry} material={materials['Black Screen']} position={[-66.307, 3.85, -46.554]} rotation={[1.571, -0.26, -1.053]} scale={[-3.413, -0.085, -2.526]} />
      <mesh geometry={nodes.vendingMachineBody.geometry} material={materials.white} position={[-20.835, 6.522, -26.973]} rotation={[2.797, -0.68, 3.06]} scale={[-6.026, -9.427, -3.719]} />
      <mesh geometry={nodes.vendingMachineScreen.geometry} material={materials['Black Screen']} position={[-20.835, 6.522, -26.973]} rotation={[2.797, -0.68, 3.06]} scale={[-6.026, -9.427, -3.719]} />
      <mesh geometry={nodes.vendingMachineBodySlot.geometry} material={materials.glass} position={[-18.324, 0.415, -22.491]} rotation={[-0.344, 0.68, 0.081]} scale={[4.137, 1.53, 0.135]} />
      <group position={[-15.429, 11.055, -28.39]} rotation={[-0.588, 0.65, 0.232]} scale={[0.645, 1.066, 0.243]}>
        <mesh geometry={nodes.Cube006.geometry} material={materials['Black Screen']} />
        <mesh geometry={nodes.Cube006_1.geometry} material={materials.payment} />
        <mesh geometry={nodes.Cube006_2.geometry} material={materials['grey keyboard']} />
      </group>
    </group>
  )
}

useGLTF.preload('/environment.glb')
